"""empty message

Revision ID: 55a420ee2533
Revises: d9fa9d22dd4e
Create Date: 2024-07-12 21:38:11.192643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a420ee2533'
down_revision = 'd9fa9d22dd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_info', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('private_info')

    # ### end Alembic commands ###
